### ISSUE TITLE
Python default/env:conda/conda root

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/datalab#15]
On the jupyterlab launcher there are three python options: "default", "conda env:conda" and "conda root". What is the difference between these? Do we need all three, or can we simplify this for the user?

**Comment by slejdops** [comment]
probably possible to customize that via nb_conda_kernels

**Comment by alimanfoo** [comment]
Discussed today with @slejdops and @idwright, two requirements come out:

(0) Currently all Python packages that we install in the user image are installed into the root conda environment. It would be better to install these into a named conda environment, so the user can then create different conda environments alongside.

(1) It would be good to simplify the list of launcher options to remove any that are redundant. Currently there are three Python launchers, all of which launch the same Python kernel.

(2) We need to understand how users create new conda environments, and how they can then launch a new Python kernel using their custom conda environment.

**Comment by alimanfoo** [comment]
Scope this issue to fixing to remove extra buttons.

**Comment by alimanfoo** [comment]
I.e., just single root environment, good enough for now.

**Comment by alimanfoo** [comment]
Fixed in GCP, only single option visible. @slejdops for future reference, can you add a comment saying how you fixed this?
