### ISSUE TITLE
User control of Dask cluster

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/datalab#24]
Can the user change the number of nodes in their Dask cluster? How do they do this?

**Comment by slejdops** [comment]
When you set up you dask cluster like in the example below you get the Manual Scaling/Adaptive Scaling panel
`from dask_kubernetes import KubeCluster
cluster = KubeCluster.from_yaml('worker-template.yaml')`

**Comment by alimanfoo** [comment]
This works.
