### ISSUE TITLE
Upload first Zarr test dataset to GCS

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/datalab#26]
Upload an initial Zarr dataset to GCS to have something to write some examples against and do some benchmarking.

**Comment by alimanfoo** [comment]
Hi @slejdops, suggest the following.

Create a new bucket to hold data from Ag1000G public data releases. Suggest to call this bucket  "ag1000g-release".

Then sync files from this path on our cluster:

```
/kwiat/vector/ag1000g/release/phase2.AR1/variation/main/zarr2/ag1000g.phase2.ar1/
```

...to this path in GCS ag1000g-release bucket:

```
/phase2/AR1/variation/main/zarr2/ag1000g.phase2.ar1/
```

When synchronizing, there are some files you can exclude. If I was doing an rsync, the arguments would be:

```
--exclude=calldata/AD --exclude=calldata/DP --exclude=calldata/GQ --exclude=calldata/MQ0
```

Hope that makes sense, drop by if anything not clear.

**Comment by slejdops** [comment]
rsync now in progress

**Comment by alimanfoo** [comment]
Out of interest, how are you doing the copy? Rcloud?

**Comment by slejdops** [comment]
I'm using rsync to transfer the data from papa to the bucked mounted via gcsfs.

**Comment by alimanfoo** [comment]
Cool. Btw I heard about this tool called rclone, maybe useful for uploads.
Also IIRC there is the gcloud cli to upload direct to GCS. At some point
may be worth comparing methods to see if one is substantially faster.

**Comment by alimanfoo** [comment]
Done.
