### ISSUE TITLE
Try preemptibles for dask workers

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/datalab#28]
Try using preemptible nodes for dask workers, test if scaling up and down works as expected. 

N.B., pangeo stopped using preemptibles because of failure to scale down, but this may be already fixed via kubernetes upgrades and/or something we can ask Hatem for help with.

**Comment by alimanfoo** [comment]
Hi @slejdops, can you take another look at this while I'm away? If we can get preemptibles to work for dask workers it could save us a lot of money.

**Comment by alimanfoo** [comment]
cc @idwright

**Comment by slejdops** [comment]
datalab.malariagen.net is now configured to schedule dask workers in its preemptible pool.
