### ISSUE TITLE
Install scikit-allel in dask worker image

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/datalab#30]
To use scikit-allel with dask it needs to be installed in the worker image. I don't think we have a dockerfile for the worker image yet? Maybe we should create one, and also consolidate the and review list of packages that we install there and in the notebook image.

**Comment by alimanfoo** [comment]
Btw @slejdops I'm pretty sure the fact that scikit-allel is not installed on the workers is the cause of the "KilledWorker" errors we saw yesterday. Here's a notebook with some examples:

https://gist.github.com/alimanfoo/7fad9309c2e88b98589b09a7415bb4a8#file-initial-tests-ipynb

**Comment by alimanfoo** [comment]
Otherwise running very smoothly! I get about the same computation speed over a genotype array stored in GCS with a cluster of 6 workers (12 processes) as I do on my 4 core (8 thread) laptop reading from on-board SSD.

**Comment by alimanfoo** [comment]
@hardingnj for our malariagen jupyterhub we have a [dockerfile](https://github.com/malariagen/jupyterhub/blob/master/dockerfiles/notebook/Dockerfile) which defines the image that runs the main notebook pod (i.e., what runs jupyterlab and where you run interactive analyses), and we need to have a dockerfile which defines the image that is used as a dask worker pod when running distributed computations. Both the notebook image and the worker image should have the same set of analysis packages installed, including numpy, scipy, scikit-allel, etc., but they currently don't. 

The notebook image needs some additional packages like jupyterlab which the worker doesn't. The worker may also need a few packages to enable it to act as a dask worker which the notebook pod doesn't need. In spite of this, IIUC Pangeo have recently decided to keep things simple and use the same image for both notebook and dask worker, which simplifies things, although @slejdops tells me this may slow things down for us a little as it makes the worker images larger than they need to be. 

@hardingnj would you be able to chat to @slejdops and start working together on:

* Should we have separate notebook and worker images, or just use same image for both?
* Review the list of Python packages currently installed in the notebook image, remove any you think are not commonly used by us for popgen and general data science so we can trim down the image size a bit.
* Probably factor out the list of Python packages into a separate file for clarity, rather than define everything in the dockerfile.
* If you decide separate images, create a new dockerfile for the worker image, and make sure the same Python packages are installed as in the notebook image.

I suspect that if we trim down the packages installed in the notebook image a bit then we might be able to get away with using the same image for both notebook and workers, but very happy to go the other way if you think better.

**Comment by hardingnj** [comment]
No problem. I'll have a look through the packages and remove any cruft- I guess how much we can get the image size down is probably a big factor in deciding which way to go.

**Comment by alimanfoo** [comment]
This has been done.
