### ISSUE TITLE
Dask dashboard links are not working

### ISSUE THREAD

**Issue by slejdops** [malariagen/datalab#33]
the  {JUPYTERHUB_SERVICE_PREFIX}proxy/{port} part is missing from the dashboard links

**Comment by alimanfoo** [comment]
Looks like this was fixed a few days ago: https://github.com/dask/distributed/pull/2242

**Comment by alimanfoo** [comment]
Confirm that installing distributed from github master resolves this.

**Comment by alimanfoo** [comment]
The fix for this was included in release 1.23.2. Newer version 1.23.3 [now available](https://distributed.readthedocs.io/en/latest/changelog.html). So need to upgrade version installed.

**Comment by alimanfoo** [comment]
This is fixed in GCP.
