### ISSUE TITLE
[Sanger] Configure 2FA authentication

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/datalab#39]
Configure datalab to use CAS authentication with 2FA enabled.

**Comment by idwright** [comment]
2FA configured against datalab.malariagen.net - configuration to be copied once we have a target URL

**Comment by roamato** [comment]
@idwright which system/provider did you end up using for the 2FA? Did you modify the MalariaGEN SSO or used external providers (e.g. GitHub, Google, ...)?

**Comment by idwright** [comment]
It's the malariagen SSO configured to use Google Authenticator

**Comment by slejdops** [comment]
2FA authentication configured and tested
