### ISSUE TITLE
ORNL demo Friday 25th Jan

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/datalab#54]
I'll be presenting to folk at Oak Ridge National Lab on Friday (25th Jan) at 5pm UK time. I'm planning to demo datalab.malariagen.net so please don't change anything between now and then! 

Also I will probably log in 30 mins ahead of time and scale up the cluster, just so I get quick allocation of worker pods.

**Comment by alimanfoo** [comment]
cc @slejdops, @idwright

**Comment by roamato** [comment]
Unless you are very late for the meeting, I guess we can close this? 😄
