### ISSUE TITLE
Change DNS on workers/pod nodes

### ISSUE THREAD

**Issue by roamato** [malariagen/datalab#57]
@slejdops 
(cc @alimanfoo)

I was trying to run the notebook in #56 but I can't load the data. The problem appears to be the end point as the pods are trying to talk to cog's "outside" IP addresses from "inside".

Workers should be using `172.18.255.1` and `.2` and `.3` for DNS servers and `host cog.sanger.ac.uk` should return:
```
cog.sanger.ac.uk has address 172.27.6.12
cog.sanger.ac.uk has address 172.27.6.15
cog.sanger.ac.uk has address 172.27.6.18
```

You can verify that it works if the following snippet runs quickly and with no errors:
```python
import s3fs

storage_path = 'ag1000g-release/phase2/AR1/variation/main/zarr2/ag1000g.phase2.ar1'

s3 = s3fs.S3FileSystem(anon=True, client_kwargs=dict(region_name='us-east-1', endpoint_url="https://cog.sanger.ac.uk"))
store = s3fs.S3Map(root=storage_path, s3=s3, check=False)
```

**Comment by roamato** [comment]
I've been advised to have a look [here](https://gitlab.internal.sanger.ac.uk/hc7/kubespray) for a Sanger specific configuration of k8s. Somewhere in there there are the specs for the DNS and whatever else it might be needed to make it work.

Also people are very responsive on the #helpme Slack channel, I suggest to start from there should you have any problem.

Rob

**Comment by slejdops** [comment]
Cool, thx

**Comment by slejdops** [comment]
I have changed the pod config to use 172.18.255.1 as the primary nameserver.

**Comment by roamato** [comment]
Thanks. I'm satisfied pods can see the correct end points, closing the issue.
