### ISSUE TITLE
Estimating costings for work done

### ISSUE THREAD

**Issue by hardingnj** [malariagen/datalab#60]
Hi @slejdops 

I recently made this PR:
https://github.com/malariagen/vector-tools/pull/18

Taking 40 workers, it takes about 45 minutes to run the 64k or so whole genome pairwise comparisons for 360 samples.

Alistair and I were wondering how much this costs in terms of compute- and is it feasible to do for all sample sets. 

Thanks!

PS possibly linked to #28

**Comment by hardingnj** [comment]
I guess this will drop substantially now we have pre-emptibles working? It would be useful to put a number on this.

**Comment by slejdops** [comment]
All dask workers are  scheduled on preemptibles.

**Comment by hardingnj** [comment]
Thanks
