### ISSUE TITLE
Upgrade datalab image to use malariagen/binder v2.4.1

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/datalab#74]
The [v2.4.1 binder release](https://github.com/malariagen/binder/tree/v2.4.1) includes the upgrade to dask and distributed v2.8.1, so we can use that to upgrade our datalab image.

**Comment by slejdops** [comment]
datalab image based on the v2.4.1 binder release built and tested.
I'll  upgrade datalab to use the new image tomorrow betwen 10 and 11 AM

**Comment by alimanfoo** [comment]
Assuming this can be closed.
