### ISSUE TITLE
Upgrade image to use malariagen/binder v2.5.0

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/datalab#79]
Hi @slejdops, can we please build a new image using the v2.5.0 binder environment.

**Comment by slejdops** [comment]
Hi @alimanfoo.

I have created a new image based on binder v2.5.0. I had to downgrade jupyterlab to 1.2.4=py_0 in order to make it work.

Shall I deploy the image to datalab tonight ?

**Comment by alimanfoo** [comment]
Hi @slejdops, yes that sounds OK, please go ahead and deploy.

**Comment by alimanfoo** [comment]
Btw would be good to raise a separate issue to capture whatever was the error or problem preventing more recent version of jupyterlab working.

**Comment by slejdops** [comment]
Image based on binder v2.5.0 deployed and tested

**Comment by alimanfoo** [comment]
Thanks @slejdops :+1:
